### ISSUE TITLE
After YT-Update: No text and images on YouTube

### ISSUE THREAD

**Issue by charakterziffer** [klemens/ff-youtube-all-html5#66] opened 2017-05-10 07:52 UTC
Sporadically YouTube is giving me its new design which also can be [activated manually](https://www.youtube.com/new). While getting this new design the addon _YouTube All HTML5_ causes the page not to be shown correctly. Only the video will be loaded but no additional text, related videos, … the menu is shown and can be used, sometimes navigating around a little helps.

![empty-yt](https://cloud.githubusercontent.com/assets/7194876/25888313/f1d8e03a-3565-11e7-93ac-76fc37c757e0.png)

Deactivating _YouTube All HTML5_ results in correct loading of the video page – but is of course no solution :-)

**Comment by klemens** [comment] 2017-05-10 17:53
Yup, if I activate the new design, the site is completely broken. I will take a look if I have some time (definitely not before weekend).

**Comment by charakterziffer** [comment] 2017-05-11 16:44
Mmh, it seems that YouTube closed “the preview” of its new design today – as stated by the page I linked in my bug report. Obviously it’ll take some more time until the redesign is released officially, so this bug can be paused.

**Comment by ZatsuneNoMokou** [comment] 2017-05-12 10:50
Well, this new design is completely different, it's not surprising that it's breaking addons. It use Polymer as JavaScript page rendering, so DOM structure change.

**Comment by GreenBeard** [comment] 2017-06-07 20:47
Just wanted to say it seems that it is caused by opening a video by right click open in new tab.

**Comment by klemens** [comment] 2017-08-16 21:43
I just uploaded a new version ([github](https://github.com/klemens/ff-youtube-all-html5/releases/tag/v3.2.0-rc1), [amo](https://addons.mozilla.org/firefox/addon/youtube-all-html5/versions/3.2.0-rc1)) that contains some fixes for the new design. It should now work fine, but changing the player size and hiding annotations is currently not possible (theatre mode works fine). Also the button is not displayed. Most other features should work fine (I tested speed, volume, auto-pause, resolution and autoplay prevention).

Could you all please test if this works for you and if there are any other quirks that I missed? Thanks!

**Comment by charakterziffer** [comment] 2017-08-17 06:50
Hi Klemens,

the Version 3.2.0-rc1 seems to work fine with the new YouTube design, thanks for your work!

But (off-topic) I have to confess that I was looking around for another add-on meanwhile. HTML5 seems to be standard now on YouTube and the other add-on also blocks advertising pre-rolls, extends the video description automatically, and doesn’t use the legacy add-on format. I’m not sure about privacy because it asks to load data from the developers page, and the theater mode doesn’t work that great.

Maybe I switch back, I’m not sure at the moment. I’ll try your add-on again for some time.

**Comment by klemens** [comment] 2017-08-27 18:56
I guess you could try using both, which should *probably* work. 😅

I am closing this now, as I just uploaded a new regular version with the fixes, which will soon reviewed by mozilla. Thank you all!

**Closed by klemens** 2017-08-27 18:56 UTC
Labels: bug, fixed
