### ISSUE TITLE
black screen on youtube videos

### ISSUE THREAD

**Issue by buuf** [klemens/ff-youtube-all-html5#51] opened 2015-04-26 20:52 UTC
I love not having to use flash on youtube, but after the most up-to-date version of the add-on, black screens would suddenly show up during playback on youtube. Very sporadic.

Linux mint 17 64 bit
ff 36 and 37.

**Comment by klemens** [comment] 2015-04-27 11:55
I've heard about this issues several times now from different users, but didn't experience it myself yet. The cause is probably the not-yet-so-stable implementation of MSE, which is enabled by default now in firefox 37.
So if this happens too often and is not fixed by reloading the page, you can try turning MSE off in about:config by setting media.mediasource.enabled to false. I will implement a checkbox (or the like) in the next version of the addon for this.

**Comment by buuf** [comment] 2015-04-27 23:00
It's already false for me. I suspect its always been false.

**Comment by klemens** [comment] 2015-04-28 14:45
Hm, this is interesting. Have you tried the new alpha 3.0.0 of the addon?
I will try to reproduce this under linux.

**Comment by buuf** [comment] 2015-04-28 14:59
No I have not. I will try it and test thoroughly.

--- Original Message ---

**Comment by klemens** [comment] 2015-05-07 12:01
I just got an email from another user with the same problem, also under mint 17.
I'm going to install mint into a vm and try to reproduce this issue.
Have you tested the new alpha yet?

**Comment by authentictech** [comment] 2015-05-08 16:59
I have this problem on Ubuntu 14 but only using the new YouTube player which was in beta and now is permanent. The old player worked with this add-on with no problems.

I see a few frames of video, then a brief pause with the video loading animation, then the audio continues on with the black screen. Disabling the add-on fixes this.

**Comment by klemens** [comment] 2015-05-09 09:29
Do you mean the player with the transparent controls? I have not seen it myself yet unfortunately.
Just to be sure, when you disable the addon, youtube also uses the html5 player or does it use its flash player then? If the latter, does this problem also occur when you disable flash (so that youtube has to fall back to html5)? Do you use any of the player size options of the addon?
And, as asked before, have you tried the latest alpha: https://github.com/klemens/ff-youtube-all-html5/releases/tag/v3.0.0alpha2 ?
Thanks!

**Comment by buuf** [comment] 2015-05-10 23:04
Yes I am using alpha2 and I now experience blinking controls on the video pretty constantly.
Have also seen a large pause in videos similiar to authentictech

**Comment by Siedlerchr** [comment] 2015-06-11 20:47
I experienced this also the first time today, maybe it was due to some yt changes.
However with the lates alpha I see the video again.
![yttransparent](https://cloud.githubusercontent.com/assets/320228/8117799/49545fb2-108b-11e5-9389-aae829f38fe6.png)

**Comment by klemens** [comment] 2015-07-14 18:27
I could now also reproduce this with the latest stable version (2.1.3). But as @Siedlerchr already noted, it seems to work with the latest alpha (3.0.0 alpha 2).
I will try to make a new stable of the addon by the end of this month, including fixing the sizing options for the new player design.

If you still have a black screen with the latest alpha, it could be a firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1150622 Turning off hardware acceleration might help (temporarily).

**Comment by buuf** [comment] 2015-07-14 18:29
I'm using the latest alpha and I still get the bug.





From: Klemens Schölhorn

Sent: Tuesday, July 14, 13:27

Subject: Re: [ff-youtube-all-html5] black screen on youtube videos (#51)

To: klemens/ff-youtube-all-html5

Cc: buuf



I could now also reproduce this with the latest stable version (2.1.3). But as @Siedlerchr already noted, it seems to work with the latest alpha (3.0.0 alpha 2).

I will try to make a new stable of the addon by the end of this month, including fixing the sizing options for the new player design.


If you still have a black screen with the latest alpha, it could be a firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1150622 Turning off hardware acceleration might help (temporarily).

**Comment by klemens** [comment] 2015-07-14 18:35
As I noted, this could also be a firefox box. You could try disabling both my addon AND the flash player in the addon manager (then youtube has to fall back to using html5) and see of you still get a black screen.

**Comment by buuf** [comment] 2015-07-14 18:47
I no longer experience this bug using the latest alpha, at least for the past few weeks. I will try to turn off HW accelleration if it happens again and reoprt my findings.

**Comment by klemens** [comment] 2015-08-11 15:58
The new stable version 3.0.0 was just reviewed by mozilla and will be available through auto-update in the coming days. (note that this only works if you don't have any beta installed, however the latest stable and beta are identical)

**Closed by klemens** 2015-08-11 15:58 UTC
Labels: bug
